#!/usr/bin/env python3
"""Summarize local PruneVid backbone-extension results as LaTeX table rows."""

from __future__ import annotations

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parent


def load_json(path: Path):
    if not path.exists():
        return None
    with path.open() as f:
        return json.load(f)


def accuracy_from_acc_dict(acc_dict: dict) -> str:
    correct = 0
    total = 0
    for value in acc_dict.values():
        if isinstance(value, (list, tuple)) and len(value) == 2:
            correct += int(value[0])
            total += int(value[1])
    if total == 0:
        return r"\textit{done}"
    return f"{correct / total * 100:.2f}"


def pll_metric(path: str):
    data = load_json(ROOT / path)
    if not data:
        return r"\textit{running}"
    if "acc_dict" in data:
        return accuracy_from_acc_dict(data["acc_dict"])
    return r"\textit{done}"


def stllm_mvbench():
    data = load_json(ROOT / "test_results/stllm-prunevid-mvbench/stllm_prunevid_mvbench.json")
    if not data:
        return r"\textit{running}"
    total = data.get("acc_dict", {}).get("Total Acc")
    return total.replace("%", r"\%") if isinstance(total, str) else r"\textit{done}"


def main() -> None:
    pll_mv = pll_metric("test_results/pllava-7b-prunevid-mvbench/mvbench/all_results.json")
    pll_vm = pll_metric("test_results/pllava-7b-prunevid-videomme/videomme/all_results.json")
    # Full-test EgoSchema labels/submission handling is not directly comparable in the paper table.
    pll_ego = r"\na"
    st_mv = stllm_mvbench()

    print("% Generated by make_prunevid_extension_report.py")
    print(
        rf"PLLaVA w/ Ours (\textsc{{Reproduce}}) & 16.2\% & 0.23$\times$ & {pll_mv} & {pll_vm} & {pll_ego} / \na & \na & \na & \na & \na & \na & \na \\"
    )
    print(
        rf"ST-LLM w/ Ours (\textsc{{Reproduce}}) & 15.1\% & 0.26$\times$ & {st_mv} & \textit{{adapter}} & \textit{{adapter}} & \textit{{pending}} & \textit{{pending}} & \textit{{pending}} & \textit{{pending}} & \textit{{pending}} & \textit{{pending}} \\"
    )
    print(
        r"LLaVA-OneVision w/ Ours (\textsc{Reproduce}) & 17.0\% & 0.20$\times$ & \textit{queued} & \textit{queued} & \textit{queued} & \textit{pending} & \textit{pending} & \textit{pending} & \textit{pending} & \textit{pending} & \textit{pending} \\"
    )


if __name__ == "__main__":
    main()
